baseURL: https://wrufei0525.netlify.app/
languageCode: en-us
title: Rufei Wang's Portfolio Website
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: 
    title: Rufei Wang's Website
  blog: {}
  contact:
    address:
      - city: London
        country: United Kingdom
        street: Gloucester Place
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: wang.rfe@gmail.com
        title: Email
    enable: yes
    phone:
      - phone: 
        title: Phone
  custom_css: []
  custom_js: []
  # description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
  # copyright: Company Name
    enable: yes
   # quicklinks:
     # - alt: HTML5 UP
      #  text: 'Design: '
      #  url: https://www.html5up.net
    social:
      # - icon: fa-twitter
      #  label: Twitter
      #   url: https://twitter.com/emilywrf0525
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/rufei-wang-900a30159
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/wrufei/
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/profile.php?id=100010710993221&sk=about
      - icon: fa-github
        label: GitHub
        url:  https://github.com/wrufei
  image: ''
  name: 
  navigation:
    button1:
      - name: About Me
        url: blogs/about_me
    #button2:
     # - name: About ME
     #   url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
     # - name: Generic Blog
     #   url: blogs/ipsum
     # - name: Elements
      #  url: elements.html
    menu: Menu
    subtitle: PORTFOLIO WEBSITE
    title: RUFEI 
  tiles:
    enable: yes
    showcase:
      - image: pic02.jpg
        subtitle: My CV, Academic Background, Work Experience and MORE
        title: About Me
        url: blogs/about_me
      - image: pic06.jpg
        subtitle: Snowboarder, Skateboarder, Drummer, Basketballer, Self-Taught Bartender and MORE
        title: Hobbies and Lifestyle
        url: blogs/hobbies
      - image: pic03.jpg
        subtitle: Analysis of Movie Ratings Using IMDB Dataset
        title: Data Analytic Project Showcase I
        url: blogs/project1
      - image: pic04.jpg
        subtitle: Share of Renewable Energy Production
        title: Data Analytic Project Showcase II
        url: blogs/project2b
      - image: pic05.jpg
        subtitle: Excess Rentals in TfL Bike Sharing
        title: Data Analytic Project Showcase III
        url: blogs/project3
      - image: lbs.jpg
        subtitle: MAM at LBS & BSc Economics at LSE
        title: University Life in London
        url: blogs/uni_life_london 
        
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Blogs about my academic background, work experience, hobbies, past projects and my university life in London. Stay posted!"
    title: My Blogs Overview
    url: blogs
