baseURL: https://wrufei0525.netlify.app/
languageCode: en-us
title: Rufei Wang's Portfolio Website
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: 
    title: Rufei Wang's Website
  blog: {}
  contact:
    address:
      - city: London
        country: United Kingdom
        street: Gloucester Place
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: wang.rfe@gmail.com
        title: Email
    enable: yes
    phone:
      - phone: 
        title: Phone
  custom_css: []
  custom_js: []
  # description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
  # copyright: Company Name
    enable: yes
   # quicklinks:
     # - alt: HTML5 UP
      #  text: 'Design: '
      #  url: https://www.html5up.net
    social:
      # - icon: fa-twitter
      #  label: Twitter
      #   url: https://twitter.com/emilywrf0525
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/rufei-wang-900a30159
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/wrufei/
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/profile.php?id=100010710993221&sk=about
      - icon: fa-github
        label: GitHub
        url:  https://github.com/wrufei
  image: ''
  name: 
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: My CV
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: pic02.jpg
        subtitle: My CV, Academic Background, Work Experience and MORE
        title: About Me
        url: blogs/about_me
      - image: pic06.jpg
        subtitle: Snowboarder, Skateboarder, Drummer, Basketballer, Self-Taught Bartender and MORE
        title: Hobbies and Lifestyle
        url: blogs/risk_return
      - image: pic03.jpg
        subtitle: Analysis of Movie Ratings Using IMDB Dataset
        title: Data Analytic Project Showcase I
        url: blogs/project1
      - image: pic04.jpg
        subtitle: Share of Renewable Energy Production
        title: Data Analytic Project Showcase II
        url: blogs/hobbies_and_lifestyle
      - image: pic05.jpg
        subtitle: 
        title: TFL
        url: blogs/hobbies_and_lifestyle
      - image: lbs.jpg
        subtitle: MAM at LBS & BSc Economics at LSE
        title: University Life in London
        url: blogs/aliquam  
        
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
      \n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \n    Pellentesque
      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      pellentesque lorem ipsum dolor. \n    Nullam et orci eu lorem consequat tincidunt.
      Vivamus et sagittis libero.\n    Mauris aliquet magna magna sed nunc rhoncus
      amet pharetra et feugiat tempus."
    title: Massa libero
    url: blogs
